parameters:
#    babaganoush_gridster.example.class: Babaganoush\GridsterBundle\Example

services:
#    babaganoush_gridster.example:
#        class: %2levelsabove_gridster.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
