parameters:
#    babaganoush_datatables.example.class: Babaganoush\DataGridsterBundle\Example

services:
#    babaganoush_gridster.example:
#        class: %2levelsabove_gridster.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
